# site settings
title: IForHunger
subtitle: Blog
email: josh@contend.church
description: "We are committed to loving the one in front of us and believing that Jesus will multiple anything that is placed in our hands. We believe for the impossible; to truly defeat hunger and lack of child care in India by going to battle each and every day through intercession and joyfully putting our feet to action. We establish, support, and organize feeding centers, orphanages, and general care for children in need."
url: "http://iforhunger.com" # the base hostname & protocol for your site
image: "assets/img/bg-banner02.jpg"

# homepage tiles
update-count: 3

# build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "assets/photos"
    values:
      image: true